name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Azure Conttiner Registry
        uses: azure/docker-login@v1
        with:
          login-server: todoappcont.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: todoappcont.azurecr.io/todoapp-backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: todoappcont.azurecr.io/todoapp-frontend:latest
      
    deploy:
      runs-on: ubutu-latest
      needs: build_and_push

      steps:
      - name: Checkout code
        uses: actions/chekout@v2

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy backend to Azure Container Apps
        run: |
          az containerapp update \
          --name backend-app \
          --resource-group ToDoAppContainer \
          --image todoappcont.azurecr.io/todoapp-backend:latest

      - name: Deploy frontend to Azure Container Apps
        run: |
          az containerapp update \
          --name frontend-app \
          --resource-group ToDoAppContainer \
          --image todoappcont.azurecr.io/todoapp-frontend:latest